name: Deploy Docsify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Docsify
        run: npm install -g docsify-cli

      - name: Build and deploy Docsify
        run: |
          cd docs
          docsify generate .
          git config --global user.email "your_email@example.com"
          git config --global user.name "Your Name"
          git add .
          git commit -m "Deploying Docsify"
          git push origin main
